Update hymofs_main.yml

diff --git a/.github/workflows/hymofs_main.yml b/.github/workflows/hymofs_main.yml
--- a/.github/workflows/hymofs_main.yml
+++ b/.github/workflows/hymofs_main.yml
@@ -228,8 +228,17 @@ jobs:
       - name: "🔧 HymoFS setup"
         working-directory: ./${{ env.kernelDir }}/${{ env.kernelName }}
         run: |
-          curl -LSs https://raw.githubusercontent.com/Anatdx/HymoFS/main/setup.sh | bash -s defconfig arch/arm64/configs/${{ env.DEFCONFIG_NAME}} 
+          # Helper
+          apply_patch() {
+            local url="$1"
+            local file=$(basename "$url")
+            curl -L -o "$file" "$url"
+            patch -p1 < "$file" || echo "::warning::Hunks failed in $file"
+            rm -f "$file"
+          }
 
+          apply_patch "https://raw.githubusercontent.com/topnotchfreaks/kernel_patches/main/0001-Implement-HymoFS-support.patch"
+          
           CONFIG_FILE="arch/arm64/configs/${{ env.DEFCONFIG_NAME }}"
           cat >> "$CONFIG_FILE" << 'EOF'
           CONFIG_HYMOFS=y
